apiVersion: v2
description: Chart Operator ServiceMonitors
name: chart-operator-extensions
version: 1.1.2
appVersion: 1.0.0
annotations:
  io.giantswarm.application.restrictions.cluster-singleton: 'true'
  io.giantswarm.application.restrictions.fixed-namespace: giantswarm
  io.giantswarm.application.restrictions.namespace-singleton: 'true'
  io.giantswarm.application.team: honeybadger
home: https://github.com/giantswarm/chart-operator-extensions
keywords:
- monitoring
type: application
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
